### ISSUE TITLE
Value too large for defined data type

### ISSUE THREAD

**Issue by rubenkr** [kholia/pst2john#1]
Machine: Debian i686

built from github with make pst2john-linux.
ran ./pst2john file.pst
sample test on file.pst (5GB contents)
output was error saying:

Error opening PST file: Value too large for defined data type
Error opening File

I tried with 
./pst2john samples/Outlook_enc.pst

output: samples/Outlook.enc.pst:$pst$b8b072c2
Password for samples/Outlook_enc.pst: 123456

What can I do to strip the file maybe to a smaller size. Maybe there is a workaround to work on bigger PST files.

I am happy to test where ever possible. Thank you very much for your great work.

**Comment by kholia** [comment]
Use a 64-bit Linux distribution and try again.

If the problem persists, see help from http://www.five-ten-sg.com/libpst/ folks.
